"""empty message

Revision ID: c8f1794a0773
Revises: cb76e6b76664
Create Date: 2024-12-19 11:26:50.994628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f1794a0773'
down_revision = 'cb76e6b76664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_info_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('message', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'business_info', ['business_info_id'], ['id'])
        batch_op.drop_column('business_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('email')
        batch_op.drop_column('content')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_info_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('review', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'business_info', ['business_info_id'], ['id'])
        batch_op.drop_column('customer_id')
        batch_op.drop_column('business_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'business_info', ['business_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['customer_id'], ['id'])
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('review')
        batch_op.drop_column('email')
        batch_op.drop_column('business_info_id')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'business_info', ['business_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['customer_id'], ['id'])
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('message')
        batch_op.drop_column('business_info_id')

    # ### end Alembic commands ###
